export {
  ArrowDown01Icon as ChevronDownIcon,
  ArrowRight01Icon as ArrowRightIcon,
  ArrowUpRight01Icon as ArrowUpRightIcon,
  Asterisk02Icon as AsteriskIcon,
  Calendar03Icon as CalendarIcon,
  CallIcon as PhoneIcon,
  Cancel01Icon as CloseIcon,
  Facebook01Icon as FacebookIcon,
  GlobalIcon as GlobeIcon,
  InstagramIcon,
  Linkedin01Icon as LinkedInIcon,
  Location01Icon as LocationIcon,
  Mail01Icon as MailIcon,
  Menu01Icon as MenuIcon,
  Mortarboard01Icon as MortarboardIcon,
  NewTwitterIcon as TwitterIcon,
  PlayIcon,
  QuoteUpIcon as QuoteIcon,
  Tick02Icon as CheckIcon,
  YoutubeIcon as YouTubeIcon,
} from "@hugeicons/core-free-icons";
export type { IconSvgElement } from "@hugeicons/react";
