export {
  ArrowDown01Icon as ChevronDownIcon,
  ArrowLeft01Icon as ArrowLeftIcon,
  ArrowLeft01Icon as ChevronLeftIcon,
  ArrowRight01Icon as ChevronRightIcon,
  ArrowRight01Icon as ArrowRightIcon,
  ArrowUp01Icon as ChevronUpIcon,
  ArrowUpRight01Icon as ArrowUpRightIcon,
  Asterisk02Icon as AsteriskIcon,
  Calendar03Icon as CalendarIcon,
  CallIcon as PhoneIcon,
  Cancel01Icon as CloseIcon,
  Delete02Icon as TrashIcon,
  Download01Icon as DownloadIcon,
  Facebook01Icon as FacebookIcon,
  GlobalIcon as GlobeIcon,
  InstagramIcon,
  Linkedin01Icon as LinkedInIcon,
  Location01Icon as LocationIcon,
  Mail01Icon as MailIcon,
  Menu01Icon as MenuIcon,
  Mortarboard01Icon as MortarboardIcon,
  NewTwitterIcon as TwitterIcon,
  PlusSignIcon as PlusIcon,
  QuoteUpIcon as QuoteIcon,
  Tick02Icon as CheckIcon,
  TiktokIcon as TikTokIcon,
  WhatsappIcon as WhatsAppIcon,
  YoutubeIcon as YouTubeIcon,
} from "@hugeicons/core-free-icons";
export type { IconSvgElement } from "@hugeicons/react";
