import { entryOf, isoDate } from "../identifiers";
import type { ContentImage, GalleryItem } from "../types";
import {
  auditoriumGathering,
  bachelorOrientation,
  basketballPrizeGiving,
  christmasHall,
  climatePanel,
  convocationCeremony,
  ecoClubFrame,
  eliteCompetition,
  mascotDesignEntry,
  mustangTrip,
  plantationProgramme,
  readingHall,
  readingRoom,
  schoolTransport,
  scienceLaboratory,
  serviceCamp,
  studentsOnCampus,
} from "./images";

const campusSports: ContentImage = {
  src: "/nami/campus-sports.jpg",
  alt: "Students on the NAMI sports ground during a campus tournament or sports day.",
  width: 1500,
  height: 1000,
};

const campusInfirmary: ContentImage = {
  src: "/nami/campus-infirmary.jpg",
  alt: "The NAMI campus infirmary, a small treatment room kept ready for students.",
  width: 600,
  height: 400,
};

const campusBloodDonation: ContentImage = {
  src: "/nami/campus-blood-donation.jpg",
  alt: "NAMI A-Level students at the Christmas blood donation drive, donors seated beside the donation tables on campus.",
  width: 1064,
  height: 709,
};

export const gallery: readonly GalleryItem[] = [
  {
    ...entryOf("mustang-academic-trip"),
    category: "student-life",
    institution: "college",
    title: "Mustang Academic Trip",
    image: mustangTrip,
    date: isoDate("2023-12-08"),
  },
  {
    ...entryOf("school-transport"),
    category: "campus",
    institution: "school",
    title: "School Transport",
    image: schoolTransport,
    date: null,
  },
  {
    ...entryOf("chemistry-laboratory"),
    category: "academics",
    institution: "school",
    title: "Chemistry Laboratory",
    image: scienceLaboratory,
    date: null,
  },
  {
    ...entryOf("students-on-campus"),
    category: "student-life",
    institution: "college",
    title: "Students on Campus",
    image: studentsOnCampus,
    date: null,
  },
  {
    ...entryOf("college-library"),
    category: "academics",
    institution: "institute",
    title: "College Library",
    image: readingRoom,
    date: null,
  },
  {
    ...entryOf("reading-hall"),
    category: "academics",
    institution: "college",
    title: "Reading Hall",
    image: readingHall,
    date: null,
  },
  {
    ...entryOf("auditorium-gathering"),
    category: "campus",
    institution: "college",
    title: "Auditorium Gathering",
    image: auditoriumGathering,
    date: null,
  },
  {
    ...entryOf("service-camp-sindhupalchowk"),
    category: "student-life",
    institution: "school",
    title: "Service Camp, Sindhupalchowk",
    image: serviceCamp,
    date: isoDate("2024-01-27"),
  },
  {
    ...entryOf("see-3x3-basketball-prize-giving"),
    category: "sports",
    institution: "college",
    title: "SEE 3x3 Basketball Prize-Giving",
    image: basketballPrizeGiving,
    date: isoDate("2024-05-16"),
  },
  {
    ...entryOf("christmas-at-city-campus"),
    category: "events",
    institution: "institute",
    title: "Christmas at City Campus",
    image: christmasHall,
    date: isoDate("2023-12-24"),
  },
  {
    ...entryOf("eco-club-environment-day"),
    category: "events",
    institution: "college",
    title: "Eco Club Environment Day",
    image: ecoClubFrame,
    date: isoDate("2023-06-05"),
  },
  {
    ...entryOf("mascot-design-competition"),
    category: "events",
    institution: "college",
    title: "Mascot Design Competition",
    image: mascotDesignEntry,
    date: isoDate("2023-05-03"),
  },
  {
    ...entryOf("elite-2023"),
    category: "graduation",
    institution: "institute",
    title: "ELITE 2023",
    image: eliteCompetition,
    date: isoDate("2023-03-31"),
  },
  {
    ...entryOf("climate-change-panel"),
    category: "events",
    institution: "institute",
    title: "Climate Change Panel",
    image: climatePanel,
    date: isoDate("2023-03-23"),
  },
  {
    ...entryOf("bachelors-orientation-2022"),
    category: "graduation",
    institution: "institute",
    title: "Bachelor's Orientation 2022",
    image: bachelorOrientation,
    date: isoDate("2022-11-14"),
  },
  {
    ...entryOf("convocation-2022"),
    category: "graduation",
    institution: "institute",
    title: "Convocation 2022",
    image: convocationCeremony,
    date: isoDate("2022-09-17"),
  },
  {
    ...entryOf("world-environment-day-plantation"),
    category: "student-life",
    institution: "college",
    title: "World Environment Day Plantation",
    image: plantationProgramme,
    date: isoDate("2022-06-05"),
  },
  {
    ...entryOf("campus-tournament"),
    category: "sports",
    institution: "college",
    title: "Campus Tournament",
    image: campusSports,
    date: null,
  },
  {
    ...entryOf("inter-house-match"),
    category: "sports",
    institution: "college",
    title: "Inter-House Match",
    image: campusSports,
    date: null,
  },
  {
    ...entryOf("campus-infirmary"),
    category: "campus",
    institution: "school",
    title: "Campus Infirmary",
    image: campusInfirmary,
    date: null,
  },
  {
    ...entryOf("christmas-blood-donation-drive"),
    category: "events",
    institution: "college",
    title: "Christmas Blood Donation Drive",
    image: campusBloodDonation,
    date: isoDate("2023-12-22"),
  },
];
